# Generated by Django 3.2.9 on 2021-11-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasicInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=200)),
                ('motherName', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(blank=True, max_length=200)),
                ('spouseName', models.CharField(blank=True, max_length=200, null=True)),
                ('nationaId', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=200)),
                ('religion', models.CharField(blank=True, max_length=200)),
                ('bloodgroup', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('meritalStatus', models.CharField(blank=True, max_length=200)),
                ('dateofbirth', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('uploadAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeNomineeInfo',
            fields=[
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('EmployeeBasicInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeePortal.employeebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobInfo',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('sallery', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('insuranceNumber', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tinNumber', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('confirmationDate', models.DateTimeField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('lastpaidAt', models.DateTimeField(blank=True, null=True)),
                ('joindate', models.DateTimeField(blank=True, null=True)),
                ('resignDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeBasicInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeePortal.employeebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContactInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('BasicInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeePortal.employeebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAcademicInfo',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('sallery', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('insuranceNumber', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tinNumber', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('confirmationDate', models.DateTimeField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('lastpaidAt', models.DateTimeField(blank=True, null=True)),
                ('joindate', models.DateTimeField(blank=True, null=True)),
                ('resignDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeBasicInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeePortal.employeebasicinfo')),
            ],
        ),
    ]
