# Generated by Django 3.2.9 on 2021-11-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeePortal', '0002_auto_20211109_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebasicinfo',
            name='religion',
        ),
    ]
