# Generated by Django 3.2.9 on 2021-11-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeePortal', '0003_remove_employeebasicinfo_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeebasicinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeebasicinfo',
            name='nationality',
        ),
        migrations.AddField(
            model_name='employeebasicinfo',
            name='gendercat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeePortal.gender'),
        ),
    ]
