# Generated by Django 3.2.9 on 2021-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeePortal', '0006_auto_20211109_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasicinfo',
            name='gender',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('0-', 'O Negative'), ('O+', 'O Positive')], default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeebasicinfo',
            name='meritalStatus',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('I', 'In a relationship'), ('E', 'Engagged'), ('D', 'Divorced')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeebasicinfo',
            name='nationaId',
            field=models.CharField(choices=[('BN', 'Bangladesh'), ('PL', 'Poland'), ('UAE', 'Dubai'), ('IN', 'India')], default='BN', max_length=20),
        ),
    ]
